feat:добавить функции
htmlacademy-javascript/51735-keksobooking-23 pull request #2
Opened 2021-05-31 15:47 UTC by TamaraLavrina

добавлено 2 функции, возвращающие случайные числа

2021-05-31 16:08 UTC, ArtMan-8 requested changes

2021-05-31 16:08 UTC, ArtMan-8 commented on js/main.js
> +function getRandomFloat(min, max, float = '2') {
Достаточно только этой функции )
Но нужно чуть поправить - функция возвращает строку, а нужно число.

2021-05-31 18:30 UTC, TamaraLavrina commented on js/main.js
> +function getRandomFloat(min, max, float = '2') {
поправила

2021-06-01 06:30 UTC, ArtMan-8 approved these changes

2021-06-01 06:30 UTC, merged